# Generated by Django 3.2.9 on 2022-01-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_us_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to='logo_photos')),
            ],
            options={
                'verbose_name_plural': 'About_Logo_img',
                'db_table': 'About_Logo_img',
            },
        ),
    ]
