# Generated by Django 3.2.9 on 2022-01-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_img', models.ImageField(blank=True, null=True, upload_to='destination_photos')),
                ('about_title', models.CharField(blank=True, max_length=50, null=True)),
                ('about_disc', models.TextField(blank=True, null=True)),
                ('about_intg', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
