# Generated by Django 3.2.9 on 2022-01-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='team_about',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='team_img',
            field=models.ImageField(blank=True, null=True, upload_to='destination_photos'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='team_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='about_intg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
