# Generated by Django 3.2.9 on 2022-01-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_auto_20220104_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_img', models.ImageField(blank=True, null=True, upload_to='destination_photos')),
                ('team_name', models.CharField(blank=True, max_length=50, null=True)),
                ('team_about', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='team_about',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='team_img',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='team_name',
        ),
    ]
