# Generated by Django 3.2.9 on 2022-01-01 06:03

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home_des',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_des', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Home_Des',
                'db_table': 'Home_Des',
            },
        ),
        migrations.CreateModel(
            name='home_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to='logo_photos')),
            ],
            options={
                'verbose_name_plural': 'Home_Logo',
                'db_table': 'Home_Logo',
            },
        ),
        migrations.CreateModel(
            name='HomePageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_img', models.ImageField(blank=True, null=True, upload_to='destination_photos')),
                ('destination_name', models.CharField(max_length=50)),
                ('special_offer', models.BooleanField()),
                ('about_destination', models.CharField(max_length=200)),
                ('destination_rate', models.CharField(max_length=50)),
                ('Testimonials', models.TextField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=50, null=True)),
                ('latest_news_photo', models.ImageField(blank=True, null=True, upload_to='latest_news_photos')),
                ('latest_travelling_date', models.DateField(blank=True, null=True)),
                ('news_post_text', models.TextField(blank=True, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, db_column='slug', editable=False, null=True, populate_from='destination_name')),
            ],
            options={
                'verbose_name_plural': 'Destination_Data',
                'db_table': 'Destination_Data',
            },
        ),
    ]
