# Generated by Django 3.2.9 on 2022-01-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact_By_User',
                'db_table': 'Contact_By_User',
            },
        ),
        migrations.CreateModel(
            name='contact_us_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to='logo_photos')),
            ],
            options={
                'verbose_name_plural': 'Contact_Logo_img',
                'db_table': 'Contact_logo_img',
            },
        ),
    ]
